version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: mina
      POSTGRES_PASSWORD: mina12345
    volumes:
      - /home/postgre/pgdata:/var/lib/postgresql/data
    networks:
      - jiranet

  jira1:
    image: atlassian/jira-software:8.13.4
    container_name: jira1
    environment:
      - JIRA_SHARED_HOME=/var/atlassian/application-data/jira/shared
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jiradb
      - ATL_JDBC_USER=mina
      - ATL_JDBC_PASSWORD=mina12345
      - CLUSTERED=true
      - JVM_SUPPORT_RECOMMENDED_ARGS="-Dupm.plugin.upload.enabled=true"
    volumes:
      - ~/my-jira:/var/atlassian/application-data/jira/shared
    networks:
      - jiranet
    ports:
      - "8081:8080"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - jiranet

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"  
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  
    networks:
      - jiranet

networks:
  jiranet:
    driver: bridge

volumes:
  db_data:
  grafana_data: