version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: mina
      POSTGRES_PASSWORD: mina12345
    volumes:
      - /home/postgre/pgdata:/var/lib/postgresql/data
    networks:
      - jiranet

  jira1:
    image: atlassian/jira-software:latest
    container_name: jira1
    ports:
      - "8081:8080"
    volumes:
      - ~/my-jira:/var/atlassian/application-data/jira/shared
    environment:
      - CLUSTERED=true
      - JIRA_SHARED_HOME=/var/atlassian/application-data/jira/shared
      - JIRA_NODE_ID=node1
      - EHCACHE_LISTENER_HOSTNAME=node1
      - EHCACHE_LISTENER_PORT=40002
      - EHCACHE_OBJECT_PORT=40012
      - EHCACHE_PEER_DISCOVERY=default
    depends_on:
      - postgres
    networks:
      - jiranet

  jira2:
    image: atlassian/jira-software:latest
    container_name: jira2
    ports:
      - "8082:8080"
    volumes:
      - ~/my-jira:/var/atlassian/application-data/jira/shared
    environment:
      - ATL_CLUSTER_NAME=jira-cluster
      - ATL_CLUSTER_NODE_ID=jira-node2
      - ATL_DB_TYPE=postgres72
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jiradb
      - ATL_JDBC_USER=mina
      - ATL_JDBC_PASSWORD=mina12345
      - CLUSTERED=true
      - JIRA_SHARED_HOME=/var/atlassian/application-data/jira/shared
      - JIRA_NODE_ID=node2
      - EHCACHE_LISTENER_HOSTNAME=node2
      - EHCACHE_LISTENER_PORT=40002
      - EHCACHE_OBJECT_PORT=40012
      - EHCACHE_PEER_DISCOVERY=default
    depends_on:
      - postgres
    networks:
      - jiranet                        
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - jiranet

networks:
  jiranet:
    driver: bridge
volumes:
  db_data:
