# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'Jira app metrics'
    scheme: http
    metrics_path: '/plugins/servlet/prometheus/metrics'
    static_configs:
     - targets: ["jira1:8080"]